spring.config.import=classpath:.secret.properties

spring.application.name=spring-gift
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.
spring.jpa.properties.hibernate.auto_quote_keyword=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http.wire=DEBUG

# MD\uC640 \uD611\uC758\uD574\uC11C \uC0AC\uC6A9\uD574\uC57C \uD558\uB294 \uB2E8\uC5B4
forbidden_words=\uCE74\uCE74\uC624

# JWT \uBC1C\uD589 \uBE44\uBC00\uD0A4
jwt_key=012345678901234567890123456789qq
aes_key=00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff